#server:
#  port: 9090
spring:
  datasource:
    username: root
    password: 151476
    url: jdbc:mysql://localhost:3306/cuisine?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=FALSE
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring:
#  datasource:
#    username: bhIMS
#    password: Bhims88872567.
#    url: jdbc:mysql://47.97.155.171:3306/bhsystemdb?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=FALSE
#    driver-class-name: com.mysql.cj.jdbc.Driver



